/**
 * 도메인별 네이밍 컨벤션: {DOMAIN}_{CATEGORY}_{SPECIFIC}
*/

export const ERROR_CODES = {
    // 인증 관련 (AUTH_xxx_xxx)
    AUTH: {
        // 로그인 관련
        INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
        EMAIL_NOT_CONFIRMED: 'AUTH_USER_NOT_FOUND',
        EMAIL_ADDRESS_INVALID: 'AUTH_ACCOUNT_LOCKED',
        TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
        
        // // 회원가입 관련
        // SIGNUP_EMAIL_EXISTS: 'AUTH_SIGNUP_EMAIL_EXISTS',
        // SIGNUP_WEAK_PASSWORD: 'AUTH_SIGNUP_WEAK_PASSWORD',
        // SIGNUP_EMAIL_UNVERIFIED: 'AUTH_SIGNUP_EMAIL_UNVERIFIED',
        
        // // 토큰 관련
        // TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
        // TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
        // TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
        
        // // 권한 관련
        // PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
        // ROLE_INSUFFICIENT: 'AUTH_ROLE_INSUFFICIENT',
    },
    
    // // 항공편 관련 (FLIGHT_xxx_xxx)
    // FLIGHT: {
    //     // 조회 관련
    //     SEARCH_NO_RESULTS: 'FLIGHT_SEARCH_NO_RESULTS',
    //     SEARCH_INVALID_DATE: 'FLIGHT_SEARCH_INVALID_DATE',
    //     SEARCH_INVALID_ROUTE: 'FLIGHT_SEARCH_INVALID_ROUTE',
        
    //     // 상세 정보
    //     DETAIL_NOT_FOUND: 'FLIGHT_DETAIL_NOT_FOUND',
    //     DETAIL_UNAVAILABLE: 'FLIGHT_DETAIL_UNAVAILABLE',
        
    //     // 추적 관련
    //     TRACKING_NOT_AVAILABLE: 'FLIGHT_TRACKING_NOT_AVAILABLE',
    //     TRACKING_OUTDATED: 'FLIGHT_TRACKING_OUTDATED',
        
    //     // 외부 API
    //     API_UNAVAILABLE: 'FLIGHT_API_UNAVAILABLE',
    //     API_RATE_LIMITED: 'FLIGHT_API_RATE_LIMITED',
    //     API_PARSE_ERROR: 'FLIGHT_API_PARSE_ERROR',
    // },
    
    // // 네트워크 관련 (NETWORK_xxx_xxx)
    // NETWORK: {
    //     CONNECTION_FAILED: 'NETWORK_CONNECTION_FAILED',
    //     CONNECTION_TIMEOUT: 'NETWORK_CONNECTION_TIMEOUT',
    //     CONNECTION_REFUSED: 'NETWORK_CONNECTION_REFUSED',
    //     DNS_RESOLUTION_FAILED: 'NETWORK_DNS_RESOLUTION_FAILED',
    //     SSL_HANDSHAKE_FAILED: 'NETWORK_SSL_HANDSHAKE_FAILED',
    // },
    
    // // 검증 관련 (VALIDATION_xxx_xxx)
    // VALIDATION: {
    //     // 필드 검증
    //     FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
    //     FIELD_INVALID_FORMAT: 'VALIDATION_FIELD_INVALID_FORMAT',
    //     FIELD_TOO_LONG: 'VALIDATION_FIELD_TOO_LONG',
    //     FIELD_TOO_SHORT: 'VALIDATION_FIELD_TOO_SHORT',
        
    //     // 특정 타입 검증
    //     EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
    //     PHONE_INVALID: 'VALIDATION_PHONE_INVALID',
    //     DATE_INVALID: 'VALIDATION_DATE_INVALID',
    //     PASSWORD_WEAK: 'VALIDATION_PASSWORD_WEAK',
    // },
    
    // // 서버 관련 (SERVER_xxx_xxx)
    // SERVER: {
    //     INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
    //     DATABASE_ERROR: 'SERVER_DATABASE_ERROR',
    //     DATABASE_CONNECTION_FAILED: 'SERVER_DATABASE_CONNECTION_FAILED',
    //     SERVICE_UNAVAILABLE: 'SERVER_SERVICE_UNAVAILABLE',
    //     RATE_LIMIT_EXCEEDED: 'SERVER_RATE_LIMIT_EXCEEDED',
    //     CONFIGURATION_ERROR: 'SERVER_CONFIGURATION_ERROR',
    //     DEPENDENCY_UNAVAILABLE: 'SERVER_DEPENDENCY_UNAVAILABLE',
    // },
    
    // // 클라이언트 관련 (CLIENT_xxx_xxx)
    // CLIENT: {
    //     UNEXPECTED_ERROR: 'CLIENT_UNEXPECTED_ERROR',
    //     COMPONENT_RENDER_ERROR: 'CLIENT_COMPONENT_RENDER_ERROR',
    //     STATE_CORRUPTION: 'CLIENT_STATE_CORRUPTION',
    //     BROWSER_NOT_SUPPORTED: 'CLIENT_BROWSER_NOT_SUPPORTED',
    // },
    
    // // 비즈니스 로직 (BUSINESS_xxx_xxx)
    // BUSINESS: {
    //     OPERATION_NOT_ALLOWED: 'BUSINESS_OPERATION_NOT_ALLOWED',
    //     RESOURCE_CONFLICT: 'BUSINESS_RESOURCE_CONFLICT',
    //     QUOTA_EXCEEDED: 'BUSINESS_QUOTA_EXCEEDED',
    //     FEATURE_DISABLED: 'BUSINESS_FEATURE_DISABLED',
    // }
} as const;

type ValueOf<T> = T[keyof T];
export type ErrorCode = ValueOf<ValueOf<typeof ERROR_CODES>>;